---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: souryamishra/endgame:15  # not ideal, it should be dynamic like build id
        imagePullPolicy: Always
        name: myweb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  ports:
  - port: 8765
    targetPort: 80
    protocol: TCP
  selector:
    app: myweb
  type: LoadBalancer
